language: node_js
dist: trusty
sudo: required
node_js:
  - "0.10"
before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get -qq update
  - export CHROME_BIN=google-chrome-beta
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y libgif-dev nodejs mesa-utils google-chrome-beta
  - glxinfo

before_script:
  - "./utils/build.sh"

